// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSPipes")>]
[<assembly: AssemblyProductAttribute("FSPipes")>]
[<assembly: AssemblyDescriptionAttribute("F# streaming IO library")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSPipes"
    let [<Literal>] AssemblyProduct = "FSPipes"
    let [<Literal>] AssemblyDescription = "F# streaming IO library"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
